# Generated by Django 4.2.7 on 2026-01-04 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('tasks', 'Vazifalar'), ('applicants', 'Arizachilar'), ('second_specialty', 'Ikkinchi mutaxassislik'), ('transfer', "O'qishni ko'chirish"), ('contract_given', 'Shartnoma berilgan'), ('course_applications', 'Kurs arizalari'), ('registered', "Ro'yxatdan o'tganlar"), ('offered', 'Taklif qilganlar'), ('tests', 'Testlar'), ('groups', 'Guruhlar'), ('students', 'Talabalar'), ('employees', 'Xodimlar'), ('log_system', 'Loglar')], max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module')},
            },
        ),
    ]
