# Generated by Django 4.2.7 on 2026-01-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
