# Generated by Django 4.2.7 on 2026-01-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_last_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleaccess',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Bosh sahifa'), ('monitoring', 'Monitoring'), ('groups', 'Guruhlar'), ('students', 'Talabalar'), ('results', 'Natijalar'), ('directions', "Yo'nalishlar"), ('subjects', 'Fanlar'), ('tests', 'Testlar'), ('employees', 'Xodimlar'), ('tasks', 'Vazifalar'), ('applicants', 'Arizachilar'), ('second_specialty', 'Ikkinchi mutaxassislik'), ('transfer', "O'qishni ko'chirish"), ('contract_given', 'Shartnoma berilgan'), ('course_applications', 'Kurs arizalari'), ('registered', "Ro'yxatdan o'tganlar"), ('offered', 'Taklif qilganlar'), ('log_system', 'Loglar')], max_length=50),
        ),
    ]
