# Generated by Django 4.2.7 on 2026-01-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
