# Generated by Django 4.2.7 on 2026-01-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='camera_mode',
            field=models.CharField(choices=[('default', "Global sozlamaga bo'ysunish"), ('required', 'Doimiy majburiy'), ('not_required', 'Majburiy emas')], default='default', max_length=20),
        ),
    ]
