# Generated by Django 6.0.1 on 2026-01-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Rejada'), ('active', 'Faol'), ('completed', 'Yakunlangan'), ('paused', 'Pauza')], default='scheduled', max_length=20),
        ),
    ]
