# Generated by Django 4.2.7 on 2026-01-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_camera_mode'),
        ('tests', '0002_alter_test_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='snapshots/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='students.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='tests.test')),
            ],
        ),
    ]
