# Generated by Django 4.2.7 on 2026-01-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allow_mobile_access',
            field=models.BooleanField(default=True, help_text='Telefondan kirishga ruxsat berish'),
        ),
    ]
