# Generated by Django 4.2.7 on 2026-02-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_allow_mobile_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
